language: ruby

rvm:
  - "2.0.0"
  - "2.3"

notifications:
  email: false

script: bundle exec cucumber

# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: [always|never|change] # default: change
#     on_failure: [always|never|change] # default: always

